apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: online-inference-replicaset
   labels:
     app: online-inference-replicaset
spec:
   replicas: 4
   selector:
     matchLabels:
       app: online-inference
   template:
     metadata:
       name: online-inference
       labels:
         app: online-inference
     spec:
       containers:
         - image: artemkgushev/homework2
           name: online-inference
           ports:
             - containerPort: 8000